#pragma once
//#include "SkillLookUpTables.h"

namespace m
{
    enum class eAmbientType
    {
        Lava,
        End
    };
    static std::wstring ambientSoundPaths[(int)eAmbientType::End][3] = {
        {
          L"..\\Resources\\sound\\ambient\\scene\\lava.wav",
          L"..\\Resources\\sound\\ambient\\scene\\lava.wav",
          L"..\\Resources\\sound\\ambient\\scene\\lava.wav",
        },
    };

    static std::wstring speachSoundPaths[4][3] = {
        {
            L"..\\Resources\\sound\\speach\\diablo\\diablotaunt1.wav",
        L"..\\Resources\\sound\\speach\\diablo\\diablotaunt2.wav",
        L"..\\Resources\\sound\\speach\\diablo\\diablotaunt2.wav",
        },
        {
        L"..\\Resources\\sound\\speach\\andariel\\andarieltaunt1.wav",
        L"..\\Resources\\sound\\speach\\andariel\\andarieltaunt2.wav",
        L"..\\Resources\\sound\\speach\\andariel\\andarieltaunt3.wav",
        },
                {
            L"..\\Resources\\sound\\speach\\duriel\\durieltaunt1.wav",
        L"..\\Resources\\sound\\speach\\duriel\\durieltaunt2.wav",
        L"..\\Resources\\sound\\speach\\duriel\\durieltaunt2.wav",
        },
                {
            L"..\\Resources\\sound\\speach\\mephisto\\mephistotaunt1.wav",
        L"..\\Resources\\sound\\speach\\mephisto\\mephistotaunt2.wav",
        L"..\\Resources\\sound\\speach\\mephisto\\mephistotaunt2.wav",
        },
        
    };
    enum class eBGMType
    {
        Stage1,
        Stage2,
        Stage3,
        Stage4,
        End,
    };

    static std::wstring bgmSoundPaths[(int)eBGMType::End] = {
        L"..\\Resources\\sound\\music\\wild.wav",
        L"..\\Resources\\sound\\music\\tombs.wav",
        L"..\\Resources\\sound\\music\\kurastsewer.wav",
        L"..\\Resources\\sound\\music\\diablo.wav",
    };

    enum class eSFXType
    {
        Quake,
        End,
    };

    static std::wstring sfxSoundPaths[(int)eSFXType::End] = {
        L"..\\Resources\\sound\\ambient\\Event\\quakeloop.wav",
    };

    enum class eUISoundType
    {
        ButtonClick,
        ButtonHover,
        InvenItemPickUp,
        ItemSell,
        PotionUse,
        End,
    };
    static std::wstring buttonSoundPaths[(int)eUISoundType::End] = {
        L"..\\Resources\\sound\\cursor\\button.wav",
        L"..\\Resources\\sound\\cursor\\pass.wav",
        L"..\\Resources\\sound\\cursor\\pickup.wav",
        L"..\\Resources\\sound\\item\\gold.wav",
        L"..\\Resources\\sound\\item\\potiondrink.wav",
    };

    static std::wstring itemDropSoundPaths[6] = {
        L"..\\Resources\\sound\\item\\potion.wav",
        L"..\\Resources\\sound\\item\\potion.wav",
        L"..\\Resources\\sound\\item\\wand.wav",
        L"..\\Resources\\sound\\item\\lightarmor.wav",
        L"..\\Resources\\sound\\item\\cap.wav",
        L"..\\Resources\\sound\\item\\flippy.wav",
    };

    enum class ePlayerRunSoundType
    {
        PlayerStoneRun,
        PlayerOStoneRun,
        PlayerSandRun,
        End,
    };
    static std::wstring playerRunAudioPath[(int)ePlayerRunSoundType::End][4] = {
        {
            L"..\\Resources\\sound\\ambient\\footstep\\LightIStoneRun1.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightIStoneRun2.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightIStoneRun3.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightIStoneRun4.wav",
        },
        {
            L"..\\Resources\\sound\\ambient\\footstep\\LightOStoneRun1.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightOStoneRun2.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightOStoneRun3.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightOStoneRun4.wav",
        },
        {
            L"..\\Resources\\sound\\ambient\\footstep\\LightSandRun1.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightSandRun2.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightSandRun3.wav",
            L"..\\Resources\\sound\\ambient\\footstep\\LightSandRun4.wav",
        },
    };
    enum class ePlayerVoiceSoundType
    {
        Hit,
        End,
    };
    static std::wstring playerVoiceAudioPath[(int)ePlayerVoiceSoundType::End][4] = {
       {
           L"..\\Resources\\sound\\combat\\player\\sorceress\\soft1.wav",
           L"..\\Resources\\sound\\combat\\player\\sorceress\\soft3.wav",
           L"..\\Resources\\sound\\combat\\player\\sorceress\\soft4.wav",
           L"..\\Resources\\sound\\combat\\player\\sorceress\\soft5.wav",
       },
    };
    static std::wstring skillSoundPath[37][3] = {
        {
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\novaice.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\novaice.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\novaice.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icebolt3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\icespike1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icespike2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icespike3.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blizzloop.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blizzloop.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blizzloop.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\icespike1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icespike2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\icespike3.wav",
        },
        {},

        {
        L"..\\Resources\\sound\\skill\\sorceress\\chargedbolt1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\chargedbolt2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\chargedbolt3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\telekinesis.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\telekinesis.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\telekinesis.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\novaelec.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\novaelec.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\novaelec.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\lightning1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\lightning2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\lightning3.wav",
        },
{},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\teleport.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\teleport.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\teleport.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\thunderbolt.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\thunderbolt.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\thunderbolt.wav",
        },
        {},
        {},

        {
        L"..\\Resources\\sound\\skill\\sorceress\\firebolt1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\firebolt2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\firebolt3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\infernoloop.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\infernoloop.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\infernoloop.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\fireball1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\fireball2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\fireball3.wav",
        },
        {},
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\meteorlaunch.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\meteorlaunch.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\meteorlaunch.wav",
        },
        {},
        {},

        {},

        //diablo
        {
            L"..\\Resources\\sound\\monster\\diablo\\lazer.wav",
            L"..\\Resources\\sound\\monster\\diablo\\lazer.wav",
            L"..\\Resources\\sound\\monster\\diablo\\lazer.wav",
        },
        {},
        {},

        //andariel
        {
            L"..\\Resources\\sound\\monster\\andariel\\castsmall.wav",
            L"..\\Resources\\sound\\monster\\andariel\\castsmall.wav",
            L"..\\Resources\\sound\\monster\\andariel\\castsmall.wav",
        },

        //duriel
        {},

        //mephisto
        {
            L"..\\Resources\\sound\\monster\\mephisto\\orb.wav",
            L"..\\Resources\\sound\\monster\\mephisto\\orb.wav",
            L"..\\Resources\\sound\\monster\\mephisto\\orb.wav",
        },

    };
    static std::wstring skillCrashSoundPath[37][3] = {
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact3.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact3.wav",
        },
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blizzboom1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blizzboom2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blizzboom3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\blastimpact3.wav",
        },
        {},

        // lightning
        {
        L"..\\Resources\\sound\\combat\\impact\\static1.wav",
        L"..\\Resources\\sound\\combat\\impact\\static2.wav",
        L"..\\Resources\\sound\\combat\\impact\\static3.wav",
        },
        {
        L"..\\Resources\\sound\\combat\\impact\\static1.wav",
        L"..\\Resources\\sound\\combat\\impact\\static2.wav",
        L"..\\Resources\\sound\\combat\\impact\\static3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\combat\\impact\\static1.wav",
        L"..\\Resources\\sound\\combat\\impact\\static2.wav",
        L"..\\Resources\\sound\\combat\\impact\\static3.wav",
        },
        {
        L"..\\Resources\\sound\\combat\\impact\\static1.wav",
        L"..\\Resources\\sound\\combat\\impact\\static2.wav",
        L"..\\Resources\\sound\\combat\\impact\\static3.wav",
        },
        {},
        {},
        {
        L"..\\Resources\\sound\\combat\\impact\\static1.wav",
        L"..\\Resources\\sound\\combat\\impact\\static2.wav",
        L"..\\Resources\\sound\\combat\\impact\\static3.wav",
        },
        {},
        {},

        //fire
        {
        L"..\\Resources\\sound\\skill\\sorceress\\boom1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom3.wav",
        },
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\boom1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom3.wav",
        },
        {},
                        {
        L"..\\Resources\\sound\\skill\\sorceress\\boom1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom3.wav",
        },
        {},
        {},
        {
        L"..\\Resources\\sound\\skill\\sorceress\\boom1.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom2.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\boom3.wav",
        },
        {},
        {},
    };
    static std::wstring skillCastSoundPath[9] = {
        L"..\\Resources\\sound\\skill\\sorceress\\coldcast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\coldcast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\coldcast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\eleccast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\eleccast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\firecast.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\teleport.wav",
        L"..\\Resources\\sound\\skill\\sorceress\\thundercast.wav",
        L"",
    };
    static std::wstring fireSoundPath[3] = {
        L"..\\Resources\\sound\\object\\fire2.wav",
        L"..\\Resources\\sound\\object\\fire5.wav",
        L"..\\Resources\\sound\\object\\fire6.wav",
    };
    static bool skillSoundLoop[37] = {
        false,//iceBolt,
        false,//frozenArmor,
        false,//frostNova,
        false,//iceBlast,
        false,//shiverArmor,
        false,//clacialSpike,
        true,//blizzard,
        false,//chillingArmor,
        false,//frozenOrb,
        false,//coldMastery,

        false,//chargedBolt,
        false,//staticField,
        false,//telekinesis,
        false,//nova,
        false,//lightning,
        false,//chainLightning,
        false,//teleport,
        false,//thunderStorm,
        false,//energyShield,
        false,//lightningMastery,

        false,//fireBolt,
        false,//warmth,
        false,//inferno,
        false,//blaze,
        false,//fireBall,
        false,//fireWall,
        false,//enchant,
        false,//meteor,
        false,//fireMastery,
        false,//hydra,

    };

    static std::wstring monsterSoundPath[5][14][3] = {
        //diablo
        {
            {
            L"..\\Resources\\sound\\monster\\diablo\\attack1.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\diablo\\attack2.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\diablo\\attack3.wav",//Attack1    
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\attack4.wav",//Attack2
                L"..\\Resources\\sound\\monster\\diablo\\attack5.wav",//Attack2
                L"..\\Resources\\sound\\monster\\diablo\\attack6.wav",//Attack2
            },
            {
                L"",//Block
                L"",//Block
                L"",//Block
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\gethit1.wav",//Hit
                L"..\\Resources\\sound\\monster\\diablo\\gethit2.wav",//Hit
                L"..\\Resources\\sound\\monster\\diablo\\gethit3.wav",//Hit
            },
            {
                L"",//Natural
            L"",//Natural
            L"",//Natural
            },
            {
                L"",//Run
                L"",//Run
                L"",//Run
            },
            {
                L"",//Walk
                L"",//Walk
                L"",//Walk
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\castlazer.wav",//SpecialCast
                L"..\\Resources\\sound\\monster\\diablo\\castlazer.wav",//SpecialCast
                L"..\\Resources\\sound\\monster\\diablo\\castlazer.wav",//SpecialCast
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special1
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special1
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special1
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special2
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special2
                L"..\\Resources\\sound\\monster\\diablo\\castfire.wav",//Special2
            },
            {
                L"",//Special3
                L"",//Special3
                L"",//Special3
            },

            {
                L"",//Special4
                L"",//Special4
                L"",//Special4
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\deathhit.wav",//Dead
                L"..\\Resources\\sound\\monster\\diablo\\deathhit.wav",//Dead
                L"..\\Resources\\sound\\monster\\diablo\\deathhit.wav",//Dead
            },
            {
                L"..\\Resources\\sound\\monster\\diablo\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\diablo\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\diablo\\death.wav",//ToDead
            },
        },
        //andariel
        {
                  {
            L"..\\Resources\\sound\\monster\\andariel\\attack1.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\andariel\\attack2.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\andariel\\attack3.wav",//Attack1    
            },
            {
                L"..\\Resources\\sound\\monster\\andariel\\attack2.wav",//Attack2
                L"..\\Resources\\sound\\monster\\andariel\\attack3.wav",//Attack2
                L"..\\Resources\\sound\\monster\\andariel\\attack4.wav",//Attack2
            },
            {
                L"",//Block
                L"",//Block
                L"",//Block
            },
            {
                L"..\\Resources\\sound\\monster\\andariel\\gethit1.wav",//Hit
                L"..\\Resources\\sound\\monster\\andariel\\gethit2.wav",//Hit
                L"..\\Resources\\sound\\monster\\andariel\\gethit3.wav",//Hit
            },
            {
                L"",//Natural
            L"",//Natural
            L"",//Natural
            },
            {
                L"",//Run
                L"",//Run
                L"",//Run
            },
            {
                L"",//Walk
                L"",//Walk
                L"",//Walk
            },
            {
                L"",//SpecialCast
                L"",//SpecialCast
                L"",//SpecialCast
            },
            {
                L"",//Special1
                L"",//Special1
                L"",//Special1
            },
            {
                L"",//Special2
                L"",//Special2
                L"",//Special2
            },
            {
                L"",//Special3
                L"",//Special3
                L"",//Special3
            },

            {
                L"",//Special4
                L"",//Special4
                L"",//Special4
            },
            {
                L"",//Dead
                L"",//Dead
                L"",//Dead
            },
            {
                L"..\\Resources\\sound\\monster\\andariel\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\andariel\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\andariel\\death.wav",//ToDead
            },
        },
        //duriel
        {
                 {
            L"..\\Resources\\sound\\monster\\duriel\\attack1.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\duriel\\attack2.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\duriel\\attack3.wav",//Attack1    
            },
            {
                L"..\\Resources\\sound\\monster\\duriel\\attack3.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\attack4.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\attack5.wav",//Attack2
            },
            {
                L"",//Block
                L"",//Block
                L"",//Block
            },
            {
                L"..\\Resources\\sound\\monster\\duriel\\gethit1.wav",//Hit
                L"..\\Resources\\sound\\monster\\duriel\\gethit2.wav",//Hit
                L"..\\Resources\\sound\\monster\\duriel\\gethit3.wav",//Hit
            },
            {
                L"",//Natural
            L"",//Natural
            L"",//Natural
            },
            {
                L"",//Run
                L"",//Run
                L"",//Run
            },
            {
                L"",//Walk
                L"",//Walk
                L"",//Walk
            },
            {
                L"..\\Resources\\sound\\monster\\duriel\\attack3.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\attack4.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\attack5.wav",//Attack2
            },
            {
                L"",//Special1
                L"",//Special1
                L"",//Special1
            },
            {
                L"",//Special2
                L"",//Special2
                L"",//Special2
            },
            {
                L"",//Special3
                L"",//Special3
                L"",//Special3
            },

            {
                L"",//Special4
                L"",//Special4
                L"",//Special4
            },
            {
                L"",//Dead
                L"",//Dead
                L"",//Dead
            },
            {
                L"..\\Resources\\sound\\monster\\duriel\\death1.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\death1.wav",//Attack2
                L"..\\Resources\\sound\\monster\\duriel\\death1.wav",//Attack2
            },
        },
        //mephisto
        {
                {
            L"..\\Resources\\sound\\monster\\mephisto\\attack1.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\mephisto\\attack2.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\mephisto\\attack3.wav",//Attack1    
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\attack2.wav",//Attack2
                L"..\\Resources\\sound\\monster\\mephisto\\attack3.wav",//Attack2
                L"..\\Resources\\sound\\monster\\mephisto\\attack4.wav",//Attack2
            },
            {
                L"",//Block
                L"",//Block
                L"",//Block
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\gethit1.wav",//Hit
                L"..\\Resources\\sound\\monster\\mephisto\\gethit2.wav",//Hit
                L"..\\Resources\\sound\\monster\\mephisto\\gethit3.wav",//Hit
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\loop.wav",//Natural
                L"..\\Resources\\sound\\monster\\mephisto\\loop.wav",//Natural
                L"..\\Resources\\sound\\monster\\mephisto\\loop.wav",//Natural
            },
            {
                L"",//Run
                L"",//Run
                L"",//Run
            },
            {
                L"",//Walk
                L"",//Walk
                L"",//Walk
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\cast1.wav",//SpecialCast
                L"..\\Resources\\sound\\monster\\mephisto\\cast1.wav",//SpecialCast
                L"..\\Resources\\sound\\monster\\mephisto\\cast1.wav",//SpecialCast
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\cast2.wav",//Special1
                L"..\\Resources\\sound\\monster\\mephisto\\cast2.wav",//Special1
                L"..\\Resources\\sound\\monster\\mephisto\\cast2.wav",//Special1
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\cast3.wav",//Special2
                L"..\\Resources\\sound\\monster\\mephisto\\cast3.wav",//Special2
                L"..\\Resources\\sound\\monster\\mephisto\\cast3.wav",//Special2
            },
            {
                L"",//Special3
                L"",//Special3
                L"",//Special3
            },

            {
                L"",//Special4
                L"",//Special4
                L"",//Special4
            },
            {
                L"",//Dead
                L"",//Dead
                L"",//Dead
            },
            {
                L"..\\Resources\\sound\\monster\\mephisto\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\mephisto\\death.wav",//ToDead
                L"..\\Resources\\sound\\monster\\mephisto\\death.wav",//ToDead
            },
        },
        //balrog
        {
                 {
            L"..\\Resources\\sound\\monster\\BloodLord\\attack1.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\BloodLord\\attack2.wav",//Attack1    
            L"..\\Resources\\sound\\monster\\BloodLord\\attack3.wav",//Attack1    
            },
            {
                L"",//Attack2
                L"",//Attack2
                L"",//Attack2
            },
            {
                L"",//Block
                L"",//Block
                L"",//Block
            },
            {
                L"..\\Resources\\sound\\monster\\BloodLord\\gethit1.wav",//Hit
                L"..\\Resources\\sound\\monster\\BloodLord\\gethit2.wav",//Hit
                L"..\\Resources\\sound\\monster\\BloodLord\\gethit3.wav",//Hit
            },
            {
                L"",//Natural
            L"",//Natural
            L"",//Natural
            },
            {
                L"",//Run
                L"",//Run
                L"",//Run
            },
            {
                L"",//Walk
                L"",//Walk
                L"",//Walk
            },
            {
                L"",//SpecialCast
                L"",//SpecialCast
                L"",//SpecialCast
            },
            {
                L"",//Special1
                L"",//Special1
                L"",//Special1
            },
            {
                L"",//Special2
                L"",//Special2
                L"",//Special2
            },
            {
                L"",//Special3
                L"",//Special3
                L"",//Special3
            },

            {
                L"",//Special4
                L"",//Special4
                L"",//Special4
            },
            {
                L"",//Dead
                L"",//Dead
                L"",//Dead
            },
            {
                L"..\\Resources\\sound\\monster\\BloodLord\\death1.wav",//ToDead
                L"..\\Resources\\sound\\monster\\BloodLord\\death2.wav",//ToDead
                L"..\\Resources\\sound\\monster\\BloodLord\\death3.wav",//ToDead
            },
        },
    };
}
